backend:
  name: git-gateway
  branch: gh-pages

local_backend: true

media_folder: "img/uploads"

collections:
  - name: dataset
    label: Dataset
    folder: _datasets
    create: true
    summary: "{{title}} ({{organization}})"
    view_groups:
      - label: Organization
        field: organization
    fields:
      - label: Title
        name: title
        widget: string

      - label: Organization
        name: organization
        widget: relation
        collection: organization
        value_field: "title"
        search_fields:
          - title

      - label: Description
        name: notes
        widget: text

      - label: Resources
        name: resources
        widget: list
        fields:
          - label: Resource Name
            name: name
            widget: string
          - label: URL
            name: url
            widget: string
          - label: Format
            name: format
            widget: select
            options:
              - api
              - csv
              - json
              - geojson
              - html
              - kml
              - kmz
              - shp
              - xml

  - name: organization
    label: Organization
    folder: _organizations
    create: true
    fields:
      - label: Title
        name: title
        widget: string

      - label: Description
        name: description
        widget: text

      - label: Logo
        name: logo
        widget: string

  - name: settings
    label: Settings
    delete: false
    editor:
      preview: false
    files:
      - name: config
        label: Site settings
        file: _config.yml
        fields:
          - label: Site Title
            name: title
            widget: string

          - label: Site Greeting
            name: greeting
            description: Displayed on the homepage
            widget: string

          - label: Site Description
            name: description
            widget: text

          - label: Base URL
            name: baseurl
            widget: string
